version: '3.7'

services:
  social-mysql-1:
    build:
      context: .
      dockerfile: ./server/docker/mysql/Dockerfile
      args:
        mysql_server_id: 1
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  social-mysql-2:
    build:
      context: .
      dockerfile: ./server/docker/mysql/Dockerfile
      args:
        mysql_server_id: 2
    ports:
      - "3308:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

#  social-mysql-3:
#    build:
#      context: .
#      dockerfile: ./server/docker/mysql/Dockerfile
#      args:
#        mysql_server_id: 3
#    ports:
#      - "3309:3306"
#    restart: always
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  social-chat-mysql-1:
    image: mysql:8.0.18
    ports:
      - "3326:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  social-chat-mysql-2:
    image: mysql:8.0.18
    ports:
      - "3327:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  nginx-proxy:
    build:
      context: .
      dockerfile: ./server/docker/nginx_proxy/Dockerfile
    ports:
      - "80:80"

  app-server:
    build:
      context: .
      dockerfile: ./server/docker/app_server/Dockerfile
    ports:
      - "8000:8000"
    restart: always

  provision:
    build:
      context: .
      dockerfile: ./server/docker/app_server/Dockerfile
    entrypoint: ./entrypoint.prov.sh
