version: '3'

services:
  social-mysql:
    image: mysql:8.0.18
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      #- MYSQL_ROOT_PASSWORD=pwd
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=password

  nginx-proxy:
    build:
      context: .
      dockerfile: ./server/docker/nginx_proxy/Dockerfile
    ports:
      - "80:80"

  app-server:
    build:
      context: .
      dockerfile: ./server/docker/app_server/Dockerfile
    ports:
      - "8000:8000"
    restart: always

  provision:
    build:
      context: .
      dockerfile: ./server/docker/app_server/Dockerfile
    entrypoint: ./entrypoint.prov.sh
