version: '3'

services:
  social-mysql:
    image: mysql:8.0.18
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=password

  nginx-proxy:
    image: nginx-proxy
    ports:
      - "80:80"

  app-server:
    image: app-server
    ports:
      - "8000:8000"
    restart: always

  provision:
    image: app-server
    entrypoint: ./entrypoint.prov.sh
