version: '3.7'

services:
  social-mysql:
    image: mysql:8.0.18
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      #- MYSQL_ROOT_PASSWORD=pwd
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=password
#    deploy:
#      resources:
#        limits:
#          cpus: '0.05'

  nginx-proxy:
    build:
      context: .
      dockerfile: ./server/docker/nginx_proxy/Dockerfile
    ports:
      - "80:80"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.05'

  app-server:
    build:
      context: .
      dockerfile: ./server/docker/app_server/Dockerfile
    ports:
      - "8000:8000"
    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: '0.05'

  provision:
    build:
      context: .
      dockerfile: ./server/docker/app_server/Dockerfile
    entrypoint: ./entrypoint.prov.sh
